"""added_verification_token_and_indices

Revision ID: 102b4acccd44
Revises: 996ce83634fa
Create Date: 2026-03-15 20:24:55.477574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102b4acccd44'
down_revision: Union[str, Sequence[str], None] = '996ce83634fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    # ### end Alembic commands ###
