"""added dates for experiecnes

Revision ID: 14064c67ba83
Revises: 3e3d76dde98f
Create Date: 2026-03-26 13:04:46.879712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14064c67ba83'
down_revision: Union[str, Sequence[str], None] = '3e3d76dde98f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('experiences', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiences', 'updated_at')
    op.drop_column('experiences', 'created_at')
    # ### end Alembic commands ###
