"""Added max_Rank in competitive programming

Revision ID: 2c7cd5ad7925
Revises: 5fc36fea813c
Create Date: 2026-03-18 13:06:25.644769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7cd5ad7925'
down_revision: Union[str, Sequence[str], None] = '5fc36fea813c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cp_profiles', sa.Column('rank', sa.String(), nullable=True))
    op.add_column('cp_profiles', sa.Column('max_rank', sa.String(), nullable=True))
    op.drop_column('cp_profiles', 'badge')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cp_profiles', sa.Column('badge', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cp_profiles', 'max_rank')
    op.drop_column('cp_profiles', 'rank')
    # ### end Alembic commands ###
