"""Added indices

Revision ID: 3bf52b13c358
Revises: b1b71fd1d6b8
Create Date: 2026-03-17 22:03:20.379266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf52b13c358'
down_revision: Union[str, Sequence[str], None] = 'b1b71fd1d6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'achievements', ['user_id'])
    op.create_unique_constraint(None, 'experiences', ['user_id'])
    op.create_unique_constraint(None, 'projects', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'experiences', type_='unique')
    op.drop_constraint(None, 'achievements', type_='unique')
    # ### end Alembic commands ###
