"""Added indices fixed

Revision ID: 3c330928cea6
Revises: 3bf52b13c358
Create Date: 2026-03-17 22:04:25.703569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c330928cea6'
down_revision: Union[str, Sequence[str], None] = '3bf52b13c358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('achievements_user_id_key'), 'achievements', type_='unique')
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.drop_constraint(op.f('experiences_user_id_key'), 'experiences', type_='unique')
    op.create_index(op.f('ix_experiences_user_id'), 'experiences', ['user_id'], unique=False)
    op.drop_constraint(op.f('projects_user_id_key'), 'projects', type_='unique')
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.create_unique_constraint(op.f('projects_user_id_key'), 'projects', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_experiences_user_id'), table_name='experiences')
    op.create_unique_constraint(op.f('experiences_user_id_key'), 'experiences', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.create_unique_constraint(op.f('achievements_user_id_key'), 'achievements', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
