"""Added avatar for repo

Revision ID: 3e3d76dde98f
Revises: ae5792678425
Create Date: 2026-03-22 19:43:38.078105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3d76dde98f'
down_revision: Union[str, Sequence[str], None] = 'ae5792678425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_profiles', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('repo_profiles', sa.Column('contribution_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_profiles', 'contribution_count')
    op.drop_column('repo_profiles', 'avatar')
    # ### end Alembic commands ###
