"""Added repo count

Revision ID: 5fc36fea813c
Revises: 3c330928cea6
Create Date: 2026-03-17 23:12:49.637729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc36fea813c'
down_revision: Union[str, Sequence[str], None] = '3c330928cea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_profiles', sa.Column('public_repo_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_profiles', 'public_repo_count')
    # ### end Alembic commands ###
