"""Added avatar for cp profiles

Revision ID: 858833b9b3a9
Revises: dd2440c11e42
Create Date: 2026-03-30 11:49:38.898855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858833b9b3a9'
down_revision: Union[str, Sequence[str], None] = 'dd2440c11e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cp_profiles', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cp_profiles', 'avatar')
    # ### end Alembic commands ###
