"""added event_date

Revision ID: 895da28b8a70
Revises: 8761eb8658ab
Create Date: 2026-03-16 19:27:22.410269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895da28b8a70'
down_revision: Union[str, Sequence[str], None] = '8761eb8658ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('event_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'event_date')
    # ### end Alembic commands ###
