"""Added cascade delete

Revision ID: a429b70ac4fb
Revises: da958c4d8e6f
Create Date: 2026-03-20 22:25:37.317509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a429b70ac4fb'
down_revision: Union[str, Sequence[str], None] = 'da958c4d8e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('achievements_user_id_fkey'), 'achievements', type_='foreignkey')
    op.create_foreign_key(None, 'achievements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cp_profiles_user_id_fkey'), 'cp_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'cp_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('experiences_user_id_fkey'), 'experiences', type_='foreignkey')
    op.create_foreign_key(None, 'experiences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('repo_profiles_user_id_fkey'), 'repo_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'repo_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repo_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('repo_profiles_user_id_fkey'), 'repo_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.create_foreign_key(op.f('experiences_user_id_fkey'), 'experiences', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'cp_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('cp_profiles_user_id_fkey'), 'cp_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.create_foreign_key(op.f('achievements_user_id_fkey'), 'achievements', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
