"""Added handle for repo

Revision ID: a83a3e671557
Revises: 2c7cd5ad7925
Create Date: 2026-03-19 15:55:22.163902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83a3e671557'
down_revision: Union[str, Sequence[str], None] = '2c7cd5ad7925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_profiles', sa.Column('handle', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_profiles', 'handle')
    # ### end Alembic commands ###
