"""added_forgot_password_indices

Revision ID: ce8be6bb5638
Revises: 0e06d247221c
Create Date: 2026-03-15 21:43:59.840955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8be6bb5638'
down_revision: Union[str, Sequence[str], None] = '0e06d247221c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_forgot_password_token'), 'users', ['forgot_password_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_forgot_password_token'), table_name='users')
    # ### end Alembic commands ###
