"""Added likes count for repo

Revision ID: da958c4d8e6f
Revises: a83a3e671557
Create Date: 2026-03-19 19:51:01.243295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da958c4d8e6f'
down_revision: Union[str, Sequence[str], None] = 'a83a3e671557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_profiles', sa.Column('likes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_profiles', 'likes_count')
    # ### end Alembic commands ###
