"""removed papers, only paper count is there

Revision ID: dd2440c11e42
Revises: ddf8a1d03e11
Create Date: 2026-03-29 22:06:16.565274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd2440c11e42'
down_revision: Union[str, Sequence[str], None] = 'ddf8a1d03e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_profiles', 'papers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_profiles', sa.Column('papers', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
