"""Added papers (for hugging face)

Revision ID: ddf8a1d03e11
Revises: 14064c67ba83
Create Date: 2026-03-29 19:00:48.643293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddf8a1d03e11'
down_revision: Union[str, Sequence[str], None] = '14064c67ba83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_profiles', sa.Column('papers_count', sa.Integer(), nullable=True))
    op.add_column('repo_profiles', sa.Column('papers', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_profiles', 'papers')
    op.drop_column('repo_profiles', 'papers_count')
    # ### end Alembic commands ###
